<a href="https://colab.research.google.com/github/GargiMakhe/PythonCodes_Gargi/blob/main/Practical4(Lab_Assignment).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1.Construct a 4×4 Identity Matrix using NumPy
import numpy as np

# Create 4x4 identity matrix
identity_matrix = np.identity(4)

print("4x4 Identity Matrix:")
print(identity_matrix)

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
# 2. Generate Two 3×3 Random Matrices and Perform Addition & Multiplication
import numpy as np

# Generate two 3x3 matrices with random integers from 1 to 9
A = np.random.randint(1, 10, (3,3))
B = np.random.randint(1, 10, (3,3))

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Matrix Addition
addition = A + B
print("\nMatrix Addition (A + B):")
print(addition)

# Matrix Multiplication
multiplication = np.dot(A, B)
print("\nMatrix Multiplication (A x B):")
print(multiplication)

Matrix A:
[[7 7 9]
 [8 4 2]
 [3 7 3]]

Matrix B:
[[1 7 1]
 [9 6 7]
 [3 4 2]]

Matrix Addition (A + B):
[[ 8 14 10]
 [17 10  9]
 [ 6 11  5]]

Matrix Multiplication (A x B):
[[ 97 127  74]
 [ 50  88  40]
 [ 75  75  58]]


In [3]:
# 3.Multiply a 5×3 Matrix with a 3×2 Matrix (User Input)
import numpy as np

print("Enter elements for 5x3 matrix")

A = []
for i in range(5):
    row = list(map(int, input(f"Enter 3 elements for row {i+1}: ").split()))
    A.append(row)

A = np.array(A)

print("\nEnter elements for 3x2 matrix")

B = []
for i in range(3):
    row = list(map(int, input(f"Enter 2 elements for row {i+1}: ").split()))
    B.append(row)

B = np.array(B)

print("\nMatrix A (5x3):")
print(A)

print("\nMatrix B (3x2):")
print(B)

# Matrix Multiplication
product = np.dot(A, B)

print("\nProduct Matrix (5x2):")
print(product)

Enter elements for 5x3 matrix
Enter 3 elements for row 1: 2 3 4
Enter 3 elements for row 2: 5 6 7
Enter 3 elements for row 3: 8 9 10
Enter 3 elements for row 4: 11 12 13
Enter 3 elements for row 5: 14 15 16

Enter elements for 3x2 matrix
Enter 2 elements for row 1: 1 2 
Enter 2 elements for row 2: 3 4
Enter 2 elements for row 3: 5 6

Matrix A (5x3):
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Matrix B (3x2):
[[1 2]
 [3 4]
 [5 6]]

Product Matrix (5x2):
[[ 31  40]
 [ 58  76]
 [ 85 112]
 [112 148]
 [139 184]]
